version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/hello-autogen-python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@me"
    labels:
      - "dependencies"
      - "python"

  # Java dependencies  
  - package-ecosystem: "maven"
    directory: "/hello-autogen-java"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@me"
    labels:
      - "dependencies"
      - "java"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"